; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DSE Reminder"
#define MyAppVersion "1.0"
#define MyAppPublisher "Matt Mulholland"
#define MyAppExeName "Reminder.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{019AE265-F58F-409B-A303-DB401F9E5241}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup
SetupIconFile=C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\1368449701_56268.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\Reminder.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\1368449701_56268.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\Reminder.application"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\Reminder.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Matt\Desktop\Reminder\Application Files\Reminder_1_0_0_1\Reminder.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

